gitSafeReplacementChar: '-'
branchName: '${issue.number}-${issue.title}'
# openPR: true
mode: chatops
branches:
  - label: bug
    skip: false
  - label: enhancement
    skip: false
  - label: '*'
    skip: true
